### ISSUE TITLE
希望能支持打桩第三方包的私有结构体方法

### ISSUE THREAD

**Issue by changmu** [agiledragon/gomonkey#125]
希望能支持这个特性：在第三方包里有个接口A，有个它的私有实现a，且在包外获取不到a的指针，这时希望能对a的方法进行打桩

**Comment by wengran2014** [comment]
赞同👍

**Comment by agiledragon** [comment]
可以实现接口A的公有实现A1，在测试中将A1注入到第三方包替代A接口，对A1的打桩就是对私有实现a的打桩
