### ISSUE TITLE
release-2.10有问题

### ISSUE THREAD

**Issue by kaifeng666** [agiledragon/gomonkey#133]
# github.com/agiledragon/gomonkey/v2
../../../../../../../pkg/mod/github.com/agiledragon/gomonkey/v2@v2.10.0/jmp_loong64.go:20:6: buildJmpDirective redeclared in this block
	previous declaration at ../../../../../../../pkg/mod/github.com/agiledragon/gomonkey/v2@v2.10.0/jmp_amd64.go:3:42

2.9可以正常使用，本机MacOs 11.7.4   CPU 2.6 GHz 六核Intel Core i7

**Comment by agiledragon** [comment]
Please take a look @abner-chenc  @zhangguanzhang
https://github.com/agiledragon/gomonkey/issues/129

**Comment by zhangguanzhang** [comment]
看着像是go build tag错了

**Comment by zhangguanzhang** [comment]
```golang
//go:build loong64
// +build loong64
```
