### ISSUE TITLE
是否有并发问题

### ISSUE THREAD

**Issue by xialonghua** [agiledragon/gomonkey#139]
1. 对A方法插装A逻辑
2. 单测
3. reset
4. 再次对A方法插装B逻辑
5. 单测
6. reset

当执行单测时5的单测会使用A逻辑，看着像并发问题？

**Comment by agiledragon** [comment]
A方法具有全局属性，打桩不是协程安全的，建议串行执行

**Comment by xialonghua** [comment]
A方法如果是某个实例的也不是协程安全的吗,如下
type IXXinterface {
func A()
}
type XX struct {}
func (x *XX) A(){}

**Comment by xialonghua** [comment]
liao
