### ISSUE TITLE
mock not effect, but effected in debug mode

### ISSUE THREAD

**Issue by kakisong** [agiledragon/gomonkey#15]
```
func A() {
	fmt.Println("real function")
}
```

```
func TestA(t *testing.T) {
	gomonkey.ApplyFunc(A, func() {
		fmt.Println("mock function")
	})
	A()
}
```

when run this test case, it print **real function**
when debug this test case, it print **mock function**

**Comment by Suvirap** [comment]
我也遇到了这个问题， 所以是啥原因啊？或者说该怎么生效呢？

**Comment by betterwinsone** [comment]
@kakisong  我也遇到这个问题，请问你是怎么解决的

**Comment by paulschroeder-tomtom** [comment]
Me too 😥

**Comment by agiledragon** [comment]
Please see the README that gomonkey fails to patch a function or a member method if inlining is enabled, please running your tests with inlining disabled by adding the command line argument that is -gcflags=-l(below go1.10) or -gcflags=all=-l(go1.10 and above).
