### ISSUE TITLE
Is it possible to add a `init` func to check whether `-gcflags=all=-l` is in `os.Args`?

### ISSUE THREAD

**Issue by Ericwww** [agiledragon/gomonkey#160]
Like this

```golang
func init() {
	if !slices.Contains(os.Args, "-gcflags=all=-l") {
		fmt.Println("WARNING: inline is enabled, some gomonkey patch will failed")
		os.Exit(1)
	}
}
```

I think this would remind developers to add `-gcflags=all=-l`.

But I'm not sure if this will affect `go build`, and judging from the current situation, my conclusion is that it won't.

**Comment by xhd2015** [comment]
Hi Eric, go-monkey is not aware of build flags. However, a new mock library supports what you are saying: https://github.com/xhd2015/xgo

**Comment by agiledragon** [comment]
@Ericwww It is a good idea, thank you!

**Comment by agiledragon** [comment]
@Ericwww You can commit a PR:
func init() {
    if !slices.Contains(os.Args, "-gcflags=all=-l") {
        fmt.Println("WARNING: inline is enabled, some gomonkey patches may be failed!")
    }
}

Remember to run tests before committing your changes.
