### ISSUE TITLE
Intellij IDEA中，如何对所有go test命令都设置`-gcflags=all=-l`参数？

### ISSUE THREAD

**Issue by 16RadioWave** [agiledragon/gomonkey#164]
readme里说避免內联使gomonkey失效需要这个参数，Run  -> Edit Configurations...里面可以添加运行配置，但只能对单个文件，有没有办法对所有test都配置这个参数？

**Comment by For-ACGN** [comment]
左下角有一个template 配置模板，可以在那里配置，后面跑的新测试都会应用配置
