### ISSUE TITLE
测试过程中GC可能导致panic

### ISSUE THREAD

**Issue by RYAN--LEE** [agiledragon/gomonkey#23]
apply的时候生成的中间函数是临时变量，过程中遇到gc之后，再调用测试函数会出现panic

**Comment by agiledragon** [comment]
你确定？产品代码运行过程中GC会导致panic吗？

**Comment by RYAN--LEE** [comment]
执行过程中遇到了，平时使用过程中偶现，在patch和执行之间gc或者等两分钟强制gc会必现。看了逻辑应该是中间创建的函数只做了地址拷贝，没有被变量引用，gc时可能被释放。尝试把getDoubleFunc 出来的内容保存一份后，就不会出现了。

**Comment by RYAN--LEE** [comment]
d := getDoubleFunc(funcType, outputs)
return this.ApplyCore(t, d)
--------------
这个d 在ApplyCore里只使用了地址，没有做引用到本身，gc的时候可能会被释放掉

**Comment by agiledragon** [comment]
嗯，可以提个PR

**Comment by agiledragon** [comment]
v2.0.2
