### ISSUE TITLE
请问可以重复打桩吗？

### ISSUE THREAD

**Issue by folivoramao** [agiledragon/gomonkey#26]
比如被测函数为a，在a中依次调用了2次函数b，分别对这两个函数b打桩吗？

**Comment by agiledragon** [comment]
不需要。
以函数为例：使用ApplyFunc给b打一个桩，多次调用b都返回同样的桩；使用ApplyFuncSeq给b打序列桩，多次调用b返回不同的桩。

**Comment by folivoramao** [comment]
谢谢
