### ISSUE TITLE
能否再简化gomonkey的测试范例，不要使用convey包

### ISSUE THREAD

**Issue by AosPassword** [agiledragon/gomonkey#27]
大佬，我在给新人安利使用gomonkey进行单元测试的时候，我让他们到test文件夹下的官方范例中进行学习。
但是新人反应，gomonkey的官方教程中使用到了convey，但是他们并不了解convey，convey包给他们阅读代码带来了较大的不便性，也不太愿意再花费时间再去花时间学习convey，甚至有些新人误以为convey和gomonkey是耦合的。
大佬您看能不能把test包下的测试范例修改成不含有convey包的形式，可以降低学习的成本，方便新人入门。

**Comment by agiledragon** [comment]
这个是测试用例，不仅仅是范例。gomonkey作为打桩框架经常和测试框架配对使用，打桩框架既可以用goconvey，也可以用testify等。
goconvey用起来应该很简单，可以参考我简书上的文章《GoConvey框架使用指南》，建议学习一下。
不使用测试框架，只在main函数中写gomonkey的范例也可以，但不那么直观和优雅，暂不考虑。

**Comment by AosPassword** [comment]
感谢大佬回复和指导。
不过我个人的观点认为，test文件夹下的测试用例毕竟是作为一个类似于指导新人入门的形式，感觉可能【降低新人入门门槛】这一点相比起【写的更为直观和优雅一点】更为重要。不过这也只算是个人观念上的不同，我也只是提一下。
