### ISSUE TITLE
apply_interface_reused_test.go有错

### ISSUE THREAD

**Issue by danyawen** [agiledragon/gomonkey#49]
test/apply_interface_reused_test.go第20行应该是	db := fake.NewDb("etcd")，而不是db := fake.NewDb("mysql")，请大神检查一下

**Comment by agiledragon** [comment]
这个并不是笔误，而是故意为之，强调的是行为的模拟，仅依赖Db任一具体的实现，至于具体是Etcd还是Mysql或者其它并不重要，只要有一个即可。假设用户要生成一个具体类型为Mysql的Db对象，串联ApplyFunc和ApplyMethod两个API，巧妙借用Db的任一实现类（比如Etcd）可完成打桩来模拟mysql的任意行为。
