### ISSUE TITLE
how to support arm64

### ISSUE THREAD

**Issue by HobbyBear** [agiledragon/gomonkey#50]
I want to run it on my apple m1,but it can not work.

**Comment by agiledragon** [comment]
You can add a go file and name it jmp_arm64.go. It is more complex than amd64. The length of the arm64 instruction is only 32 bits, and the instruction cannot store such a large immediate value. You must first load the parameter from the stack to the r27 register, and then b r27. Remember to replace instructions with instruction codes.
I don't have a apple m1 ，you can try to solve it.

**Comment by sirkon** [comment]
https://github.com/agiledragon/gomonkey/issues/39 @HobbyBear

**Comment by agiledragon** [comment]
Have you sloved the problem? @sirkon

**Comment by sirkon** [comment]
I am not solved it. Get segmentation fault due to paging and that's all. The app stops with segfault when I try to write into a code segment.

**Comment by agiledragon** [comment]
#10  @sirkon

**Comment by sirkon** [comment]
tried this, won't help

**Comment by agiledragon** [comment]
Arm64 is fully supported in the v2.2.0.
