### ISSUE TITLE
为什么总出现单独一个方法测试通过，多个方法或多个test文件一起测试会有一些panic

### ISSUE THREAD

**Issue by hugo-space** [agiledragon/gomonkey#60]
panic: double seq is less than call seq [recovered]
	panic: double seq is less than call seq

**Comment by agiledragon** [comment]
Each test is independent, repeatable, and the pre and post should be complete. The reason for this error is that the length of patches of a specified sequence is less than the number of calls. You should make sure that the length of  patches of a specified sequence is equal to the number of calls for a certain test.

**Comment by hauringu** [comment]
> Each test is independent, repeatable, and the pre and post should be complete. The reason for this error is that the length of patches of a specified sequence is less than the number of calls. You should make sure that the length of patches of a specified sequence is equal to the number of calls for a certain test.

但是，即使当我把times设置为max int，依然会报同样的错，我想应该不是这个原因。

**Comment by agiledragon** [comment]
Strictly speaking, there is no problem if the length of the patches of a specified sequence is greater than or equal to the number of calls, which is an ideal situation. Check the test case yourself carefully.

The relevant code is as follows：
         i := 0
	len := len(slice)
	return reflect.MakeFunc(funcType, func(_ []reflect.Value) []reflect.Value {
		if i < len {
			i++
			return GetResultValues(funcType, slice[i-1]...)
		}
		panic("double seq is less than call seq")
	})

**Comment by hauringu** [comment]
> Strictly speaking, there is no problem if the length of the patches of a specified sequence is greater than or equal to the number of calls, which is an ideal situation. Check the test case yourself carefully.
> 
> The relevant code is as follows：
> 
> ```go
>          i := 0
> 	len := len(slice)
> 	return reflect.MakeFunc(funcType, func(_ []reflect.Value) []reflect.Value {
> 		if i < len {
> 			i++
> 			return GetResultValues(funcType, slice[i-1]...)
> 		}
> 		panic("double seq is less than call seq")
> 	})
> ```

是我的写法问题么，麻烦帮我看看。
[https://github.com/hauringu/GolangPractice/blob/master/com/gomonkeytest/b_test.go](url)

**Comment by hauringu** [comment]
https://github.com/hauringu/GolangPractice/blob/master/com/gomonkeytest/b_test.go

**Comment by lockdown56** [comment]
> 



> > Strictly speaking, there is no problem if the length of the patches of a specified sequence is greater than or equal to the number of calls, which is an ideal situation. Check the test case yourself carefully.
> > The relevant code is as follows：
> > ```go
> >          i := 0
> > 	len := len(slice)
> > 	return reflect.MakeFunc(funcType, func(_ []reflect.Value) []reflect.Value {
> > 		if i < len {
> > 			i++
> > 			return GetResultValues(funcType, slice[i-1]...)
> > 		}
> > 		panic("double seq is less than call seq")
> > 	})
> > ```
> 
> 是我的写法问题么，麻烦帮我看看。 [https://github.com/hauringu/GolangPractice/blob/master/com/gomonkeytest/b_test.go](url)

遇到同样的问题，请问有什么进展吗

**Comment by Bistutu** [comment]
I also encountered the same issue, sometimes it panics, and other times it works fine.

**Comment by xhd2015** [comment]
> https://github.com/hauringu/GolangPractice/blob/master/com/gomonkeytest/b_test.go

can try https://github.com/xhd2015/xgo
