### ISSUE TITLE
Add v2.2.0 to Version List

### ISSUE THREAD

**Issue by derryflag** [agiledragon/gomonkey#61]
Please add v2.2.0 to version list
It's very great to hear arm is supported in v2.2.0, however, when try to use v2.2.0, I meet error 
```go get: github.com/agiledragon/gomonkey@v2.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2```

get https://goproxy.io/github.com/agiledragon/gomonkey/@v/list will only return
v2.0.1+incompatible
v2.0.2+incompatible
But v2.2.0 is missing, could you help add it?

**Comment by agiledragon** [comment]
I have added v2.2.0 for 24 days, you can see this page that url is https://github.com/agiledragon/gomonkey/releases.
You should import gomonkey package like  "github.com/agiledragon/gomonkey/v2", and not like "github.com/agiledragon/gomonkey".  I added go.mod file for gomonkey in v2.1.0

**Comment by derryflag** [comment]
Thanks a lot, with gomonkey/v2 it works fine.
