### ISSUE TITLE
permission denied  

### ISSUE THREAD

**Issue by xnnyeYp** [agiledragon/gomonkey#76]
`err := mprotectCrossPage(target, len(bytes), syscall.PROT_READ|syscall.PROT_WRITE|syscall.PROT_EXEC)
	if err != nil {
		panic(err)
	}`

这里会panic，permission denied 

os: MacBook Pro (13-inch, M1, 2020)
M1芯片

别的issue里提供的方法我都试了， 请问有什么办法可以解决这个问题吗

**Comment by sssion** [comment]
> 

only add 'GOARCH=amd64' in Environment setting, it seems that the author not solves the problem perfectly

**Comment by agiledragon** [comment]
Please try to this method, https://github.com/agiledragon/gomonkey/issues/70
@xnnyeYp @sssion @bbrodriges @taoso
