### ISSUE TITLE
err：private method feature for all go versions

### ISSUE THREAD

**Issue by cofsonJame** [agiledragon/gomonkey#86]
gomonkey：v2.7.0
go version：17.7

[fully support private method](https://github.com/agiledragon/gomonkey/releases/tag/v2.7.0)

download gomonkey-2.7.0 , when I run  apply_private_method_test.go ,  err like this:

GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\cofson\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\cofson\AppData\Local\Temp\GoLand\___TestApplyPrivateMethod_in_github_com_agiledragon_gomonkey_v2_test__1_.test.exe github.com/agiledragon/gomonkey/v2/test #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\cofson\AppData\Local\Temp\GoLand\___TestApplyPrivateMethod_in_github_com_agiledragon_gomonkey_v2_test__1_.test.exe -test.v -test.paniconexit0 -test.run ^\QTestApplyPrivateMethod\E$ #gosetup
=== RUN   TestApplyPrivateMethod
x
Failures:

  * C:/Users/cofson/GolandProjects/gomonkey/test/apply_private_method_test.go 
  Line 30:
  Expected: 'I am hungry'
  Actual:   'I am full'
  (Should be equal)
  goroutine 19 [running]:
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:143 +0x3c
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:103 +0x5d
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:176 +0xa5
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:125 +0x5a
  github.com/agiledragon/gomonkey/v2/test.TestApplyPrivateMethod.func1.1()
  	C:/Users/cofson/GolandProjects/gomonkey/test/apply_private_method_test.go:30 +0x253
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x1b
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x177
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x2c
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x476
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000b4960)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0xfb
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000084530, 0xc0000b4900, 0xc000098108)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x16a
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x2dc
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x75
  github.com/agiledragon/gomonkey/v2/test.TestApplyPrivateMethod.func1()
  	C:/Users/cofson/GolandProjects/gomonkey/test/apply_private_method_test.go:23 +0x65
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x1b
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x177
  	C:/Users/cofson/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:110 +0xce
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x476
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x22
  github.com/jtolds/gls._m(0x59b240, 0xc000039d01)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x22
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0xc0000b4810, 0x0)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x19
  github.com/jtolds/gls.addStackTag(...)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000b4810)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd8
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000084530, 0xc0000b47b0, 0xc000092480)
  	C:/Users/cofson/go/pkg/mod/github.com/jtolds/gls@v4.

**Comment by agiledragon** [comment]
Did other test cases pass?  Did you turn off the inline switch?
I advice you to see the README firstly.

**Comment by cofsonJame** [comment]
thank you very much

**Comment by cofsonJame** [comment]
Thank you very much !



At 2022-04-07 21:57:30, "Zhang Xiaolong" ***@***.***> wrote:

Did other test cases pass? Did you turn off the inline switch?
I advice you to see the README firstly.
