### ISSUE TITLE
ApplyMethod failed without pointer

### ISSUE THREAD

**Issue by mingforpc** [agiledragon/gomonkey#88]
version: v2.0.2+incompatible

work on: mac x86

```go
import (
	"fmt"
	"github.com/agiledragon/gomonkey"
	"reflect"
	"testing"
)

type A struct {
}

func (a *A) FuncA() string {
	return "FuncA"
}

func (a A) FuncB() string {
	return "FuncB"
}

func Test(t *testing.T) {
	a := &A{}
	gomonkey.ApplyMethod(reflect.TypeOf(a), "FuncA", func(_ *A) string {
		return "FuncA1"
	})

	gomonkey.ApplyMethod(reflect.TypeOf(a), "FuncB", func(_ *A) string {
		return "FuncB1"
	})

	fmt.Println(a.FuncA())
	fmt.Println(a.FuncB())
}
```

output:

```
FuncA1
FuncB
```

How can I mock `FuncB`?  Thanks you!

**Comment by agiledragon** [comment]
func TestA(t *testing.T) {
	a := &A{}
	gomonkey.ApplyMethod(reflect.TypeOf(a), "FuncA", func(_ *A) string {
		return "FuncA1"
	})

	b := A{}  // just b
	gomonkey.ApplyMethod(reflect.TypeOf(b), "FuncB", func(_ A) string {
		return "FuncB1"
	})

	fmt.Println(a.FuncA())
	fmt.Println(a.FuncB())
}

output:

FuncA1
FuncB1
